sources:
  - id: loc_popeye_sindbad
    title: "Popeye the Sailor Meets Sindbad the Sailor"
    provider: loc
    item_url: https://www.loc.gov/item/2023602008/
    license: "LOC Free to Use and Reuse: Public Domain Films from the National Film Registry"
    license_url: https://www.loc.gov/free-to-use/public-domain-films-from-the-national-film-registry/
